apiVersion: v1
entries:
  componentstatuses-exporter:
  - apiVersion: v1
    appVersion: 0.1.5
    created: 2019-11-11T21:13:36.576303+02:00
    description: A Helm chart for componentstatuses-exporter
    digest: 8182200acdf7acb22f57270947768320739536b7a997f7aaaf569b87e211b10e
    name: componentstatuses-exporter
    urls:
    - componentstatuses-exporter-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v1
    appVersion: "1.0"
    created: 2019-11-11T21:13:36.575799+02:00
    description: A Helm chart for componentstatuses-exporter
    digest: 584cd0348f3ad53322ebf06b6c89cf61939909840314b2092520a4124ba50637
    name: componentstatuses-exporter
    urls:
    - componentstatuses-exporter-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v1
    appVersion: "1.0"
    created: 2019-11-11T21:13:36.57376+02:00
    description: A Helm chart for componentstatuses-exporter
    digest: be45ceac6512b19c54db8e0ef171a7702adb55b14d99157721fffbe977a13394
    name: componentstatuses-exporter
    urls:
    - componentstatuses-exporter-0.1.1.tgz
    version: 0.1.1
generated: 2019-11-11T21:13:36.572904+02:00
